In [2]:
import pandas as pd
import numpy as np

Q1.

In [3]:
x=np.array([5,4,3,2,1])
x

array([5, 4, 3, 2, 1])

In [4]:
mat1=np.vander(x,5)
mat1

array([[625, 125,  25,   5,   1],
       [256,  64,  16,   4,   1],
       [ 81,  27,   9,   3,   1],
       [ 16,   8,   4,   2,   1],
       [  1,   1,   1,   1,   1]])

In [5]:
def pow_vector(vec, n, increasing=False):
    
    if not increasing:
        mat = np.array([x**(n-1-i) for x in vec for i in range(n)]).reshape(vec.size,n)
    elif increasing:
        mat = np.array([x**i for x in vec for i in range(n)]).reshape(vec.size,n)
    
    return mat


In [6]:
p=np.array([5,4,3,2,1])

pow_vector(p,5,increasing=False)

array([[625, 125,  25,   5,   1],
       [256,  64,  16,   4,   1],
       [ 81,  27,   9,   3,   1],
       [ 16,   8,   4,   2,   1],
       [  1,   1,   1,   1,   1]])

In [7]:
pow_vector(p,5,increasing=True)

array([[  1,   5,  25, 125, 625],
       [  1,   4,  16,  64, 256],
       [  1,   3,   9,  27,  81],
       [  1,   2,   4,   8,  16],
       [  1,   1,   1,   1,   1]])

Q2.

In [12]:
def mov_avg(x, k):
    l=[]
    for i in range(len(x)-k+1):
        mavg=sum(x[i:i+k]) / k
        l.append(mavg)
    mavg1=np.array(l)
    return mavg1
    print(type(mavg1))
        
    

In [13]:
 a=np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])

In [14]:
a

array([  3,   5,   7,   2,   8,  10,  11,  65,  72,  81,  99, 100, 150])

In [15]:
mov_avg(a,3)

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])

In [16]:
mov_avg(p,4)

array([3.5, 2.5])